# Generated by Django 4.2.30 on 2026-06-12 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutboxReferralCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer_uid', models.CharField(max_length=12)),
                ('referee_uid', models.CharField(max_length=12)),
                ('amount', models.IntegerField(default=300)),
                ('status', models.CharField(choices=[('PENDING_SYNC', 'Pending Sync'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], default='PENDING_SYNC', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referee_uid', models.CharField(max_length=12)),
                ('referrer_uid', models.CharField(max_length=12)),
                ('reward_amount', models.IntegerField(default=300)),
                ('status', models.CharField(choices=[('PENDING_SYNC', 'Pending Sync'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], default='PENDING_SYNC', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='RW100', max_length=10, unique=True)),
                ('current_counter', models.IntegerField(default=1)),
                ('max_limit', models.IntegerField(default=999)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Referral Series',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('referred_by_uid', models.CharField(blank=True, max_length=12, null=True)),
                ('rocket_coins', models.IntegerField(default=0)),
                ('streak_count', models.IntegerField(default=0)),
                ('last_streak_claim', models.DateField(blank=True, null=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('upi_id', models.CharField(max_length=100)),
                ('amount_coins', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='api.userprofile')),
            ],
        ),
    ]
