# Generated by Django 4.2.30 on 2026-06-13 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDirectory',
        ),
    ]
